export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_TYPEPRODUCTS = "GET_TYPEPRODUCTS";
export const POST_NEWPRODUCT = "POST_NEWPRODUCT";
export const GET_SUCURSAL = "GET_SUCURSAL";
export const ADD_CART = "ADD_CART";
export const REMOVE_CART = "REMOVE_CART";
