export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_TYPEPRODUCTS = "GET_TYPEPRODUCTS";
<<<<<<< HEAD
export const POST_NEWPRODUCT = "POST_NEWPRODUCT";
=======
export const POST_FILTERPRODCTS = "POST_FILTERPRODCTS";
export const POST_PRODUCTSNAME = "POST_PRODUCTSNAME";
>>>>>>> 84f263f695aca0219085db9a68af5a334da14dc3
