export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_TYPEPRODUCTS = "GET_TYPEPRODUCTS";
export const POST_FILTERPRODCTS = "POST_FILTERPRODCTS";
export const POST_PRODUCTSNAME = "POST_PRODUCTSNAME";
